// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAICPcmQ9Kjw8Wko0KiAx6RxGxDpdxKWOU',
    appId: '1:819421689454:web:608924eae42b48df52587f',
    messagingSenderId: '819421689454',
    projectId: 'smartq-e022c',
    authDomain: 'smartq-e022c.firebaseapp.com',
    storageBucket: 'smartq-e022c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpaf3zs0A07VZ42-cw4pOOmqcXJJfm3OM',
    appId: '1:819421689454:android:e7c63521c8e4854952587f',
    messagingSenderId: '819421689454',
    projectId: 'smartq-e022c',
    storageBucket: 'smartq-e022c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6nghbjRkWTH_k7h07SBdLE2pFd8mXbes',
    appId: '1:819421689454:ios:c37fc36d35e69f9652587f',
    messagingSenderId: '819421689454',
    projectId: 'smartq-e022c',
    storageBucket: 'smartq-e022c.firebasestorage.app',
    iosBundleId: 'com.example.smartq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6nghbjRkWTH_k7h07SBdLE2pFd8mXbes',
    appId: '1:819421689454:ios:c37fc36d35e69f9652587f',
    messagingSenderId: '819421689454',
    projectId: 'smartq-e022c',
    storageBucket: 'smartq-e022c.firebasestorage.app',
    iosBundleId: 'com.example.smartq',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAICPcmQ9Kjw8Wko0KiAx6RxGxDpdxKWOU',
    appId: '1:819421689454:web:f5df683bf5f19b8152587f',
    messagingSenderId: '819421689454',
    projectId: 'smartq-e022c',
    authDomain: 'smartq-e022c.firebaseapp.com',
    storageBucket: 'smartq-e022c.firebasestorage.app',
  );
}
